#!/bin/sh

vi +FZF

# cmd = `fzf --preview 'cat {}'`

# def file_checker(path)
#   if path.empty?
#     puts 'no file selected'
#     exit 0
#   end
# end

# file_checker(cmd)

# system("#{ENV['EDITOR']} #{cmd}")
