#!/usr/bin/env perl

use strict;
use warnings;

use v5.14;

my $arg = $ARGV[0];

if ( defined $arg ) {
    chdir $arg or die "Failed to change directory to $arg: $!";
}

my $dev_cmd;

if ( -f ".projections.json" ) {
    $dev_cmd = `jq -r '."*".make' .projections.json`;
}

if ( -f "nest-cli.json" ) {
    $dev_cmd = "pkg start:dev";
}

if ( -f "next.config.js" || -f "astro.config.mjs" ) {
    $dev_cmd = "pkg dev";
}

if ( -f "Gemfile" ) {
    if ( -f "bin/rails" ) {
        $dev_cmd = "rails s";
    }
    else {
        $dev_cmd = "bin/console";
    }
}

system("tmux neww -d $dev_cmd") if defined $dev_cmd;
