#!/usr/bin/env bash

copy_cmd=""
paste_cmd=""

if [[ "$(uname)" == "Linux" ]]; then
	copy_cmd="wl-copy"
	paste_cmd="wl-paste"
else
	copy_cmd="pbcopy"
	paste_cmd="pbpaste"
fi

eval "$copy_cmd"

pane_count=$(tmux list-panes | wc -l)

edit() {
	local current_pane="$(tmux list-panes -F "#{pane_active} #{pane_pid} #{pane_current_command}" | grep "^1" | awk '{print $3}')"

	if [ "$current_pane" = "nvim" ] || [ "$current_pane" = "nvi" ] ||  [ "$current_pane" = "Vim" ] || [ "$current_pane" = "vim" ]; then
		tmux send-keys ":e $(eval "$paste_cmd")" Enter
	else
		tmux send-keys -X cancel
		tmux send-keys "vi $(eval "$paste_cmd")" Enter
	fi
}

edit

# if [ "$pane_count" -gt 1 ] && tmux list-panes -F '#{pane_current_command}' | grep -q 'Vim\|vim\|nvi\|nvim\|neovim'; then
# 	tmux select-pane -l
# 	edit
# else
# 	edit
# fi
