#!/usr/bin/env bash

query=""
for arg in "$@"; do
    query="$query+$arg"
done
query=${query:1}  # remove leading +

url="https://lite.duckduckgo.com/lite/?kd=-1&kp=-1&q=$query"

w3m -o confirm_qq=false "$url"
