#!/usr/bin/env ruby

filename = ARGV.join('-').downcase

obsidian_path = ENV['OBSIDIAN_VAULT']

create = "touch #{obsidian_path}#{filename}.md"
open_obsidian = "open obsidian://#{obsidian_path}#{filename}.md"

system("#{create} && #{open_obsidian}")
